apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{name}}"
spec:
  selector:
    matchLabels:
      app: "{{name}}"
  template:
    metadata:
      labels:
        app: "{{name}}"
    spec:
      containers:
        - name: "{{name}}"
          image: "{{{image}}}"
          env:
          - name: MICRONAUT_SERVER_PORT
            value: "8080"
          {{#dockerSecret}}
          imagePullSecrets: 
          - name: {{dockerSecret}}
          {{/dockerSecret}}
          resources:
            limits:
              cpu: "1"
              memory: "2048Mi"
          ports:
            - name: http
              containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /health/readiness
          #     port: 8080
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 3
          # livenessProbe:
          #   httpGet:
          #     path: /health/liveness
          #     port: 8080
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 10
          
          
