apiVersion: v1
kind: Service
metadata:
  name: "{{name}}"
  labels:
    app: "{{name}}"
spec:
  ports:
    - port: 8080
      name: service
      targetPort: 8080
      protocol: TCP
  selector:
    app: "{{name}}"
  type: NodePort
